version: '3'

services:


  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - postgres 
  
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.docker-compose.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - ./.docker-compose.env
    environment:
      - PGADMIN_DEFAULT_EMAILname=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  
volumes:
  postgres_data:
  pgadmin_data: